# EOA compile

# IMPORTANT. The package from eoa does not export functions and there is no documentation

# Ensure the the NAMESPACE file has these 2 lines:
# # Generated by roxygen2: fake comment so roxygen2 overwrites silently.
# exportPattern("^[^\\.]")


# don't run devtools::document

# script

path <- "C:/Users/cmurray/Git/PackageRepos/eoa/"
setwd(path)

#
newVersion <- 2.1.0

# tar.gz
devtools::build(path = path, 
                binary = FALSE, 
                args = c('--preclean'))


# Install the newly created highly useful package
# remove old package
detach("package:eoa", unload = TRUE)
remove.packages("eoa")

# install new package

install.packages(repos = NULL, file.path(path, paste0("eoa_", newVersion, ".tar.gz")))

# Require the newly minted package
require(eoa)